<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Moto G (gen 4)Moto G (gen 6)Alcatel _73e413</name>
   <tag></tag>
   <elementGuidId>5423a7d2-0eb3-4bcc-907e-474c31aae8dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#location</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='location']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>where</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>location</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Moto G (gen 4)Moto G (gen 6)Alcatel 1X (Android Go)Moto G (gen 1)Moto E (gen 1)iPhone 8 (iOS 13)iPhone 7+ (iOS 13)iPhone 6 (iOS 12)iPhone 5c (iOS 10.3)iPad 2017 (iOS 13)iPad Mini 2 (iOS 12)Dulles, VA USA (Desktop, Android, iOS)Dulles, VA - Thinkpad T430 (Chrome,Firefox,Edge,IE 11)Dulles, VA - Asus Aspire i3 2017 (Chrome,Firefox,Edge,IE 11)Dulles, VA - Raspberry Pi 3 B (Chromium,Firefox)Dulles, VA - Raspberry Pi 4 (Chromium,Firefox)Virginia - EC2 (Chrome,Firefox)Clifton, NJ (Chrome,Firefox,Opera)Orlando, FL (Chrome,Firefox,Opera)Chicago, Illinois (Chrome,Firefox,Opera)Dallas, TX (Chrome,Firefox,Opera)Lincoln, Nebraska (Chrome, Firefox, Opera)Salt Lake City, Utah - GCE (Chrome,Firefox)California - ScientiaMobile (Chrome,Firefox,IE 11)San Francisco, CA (Chrome,Firefox,Opera)California - EC2 (Chrome,Firefox)Los Angeles, CA USA (Chrome, Firefox,Opera)Toronto, Canada - EC2 (Chrome,Firefox)Toronto, Canada (Chrome,Firefox,Opera)Buenos Aires, Argentina (Firefox,Chrome)Buenos Aires, Argentina - Nodus (Firefox,Chrome)Sao Paulo, Brazil (Chrome, Firefox)Sao Paulo, Brazil - EC2 (Chrome,Firefox)Uberlândia, Minas Gerais, Brazil (Chrome, Firefox, Opera)Ireland - EC2 (Chrome,Firefox)Nottingham, East Midlands, UK (Chrome, Firefox, Opera)Maidenhead, UK (Chrome,Firefox,Opera)London, UK - EC2 (Chrome,Firefox)London, UK (Chrome,Firefox)London, UK - Atlantic.net (Chrome,Firefox,Opera)La Rioja, Spain (Chrome,Firefox,Opera)Paris - EC2 (Chrome,Firefox)Paris, France (Chrome,Firefox,IE 11)Strasburg, France (Chrome,Firefox,Opera)Brussels, BE (Chrome,Firefox,Opera)Amsterdam, NL - GCE (Chrome,Firefox)Amsterdam, NL - MeasureWorks (Chrome,Firefox,Opera)Amsterdam, NL - IISpeed (Chrome,Firefox,Opera)Frankfurt, Germany - EC2 (Chrome,Firefox)Milan, Italy - EC2 (Chrome,Firefox)Prague, Czech Republic (Chrome,Canary,Firefox)Warsaw, Poland (Chrome,Firefox,Opera)Warsaw, Poland - IDG (Chrome,Firefox,Opera)Stockholm, Sweden - EC2 (Chrome,Firefox)Stockholm, Sweden (Chrome,Firefox,Opera)Cape Town, South Africa - EC2 (Chrome,Firefox)South Africa (Chrome,Firefox)Rose Hill, Mauritius (Chrome,Firefox,Opera)Istanbul, Turkey - Cloudeos (Chrome,Firefox,Opera)Ankara, Turkey (Chrome, Firefox)Israel (Chrome,Firefox,Opera)Bahrain - EC2 (Chrome,Firefox)Dubai, UAE - Azure (Chrome, Firefox)Mumbai, India - EC2 (Chrome,Firefox)Bangkok, Thailand - Tencent (Chrome, Firefox)Singapore - EC2 (Chrome,Firefox)Jakarta, Indonesia - GCE (Chrome,Firefox)Jakarta, Indonesia (Chrome,Firefox,Opera)Hong Kong, China - EC2 (Chrome,Firefox)Beijing, China (Firefox)Taiwan, China - GCE (Chrome,Firefox)Seoul, Korea - EC2 (Chrome,Firefox)Seoul, Korea EC2 (Firefox)Tokyo, Japan - EC2 (Chrome,Firefox)Sydney - Bulletproof Networks (Chrome,Firefox,Opera)Sydney - Servers Australia (IE 10,Chrome,Canary,Firefox)Sydney - Strategy Lions (Chrome,Firefox,Opera)Sydney - Dexecure (Chrome,Firefox)Sydney, Australia - EC2 (Chrome,Firefox)Melbourne, Australia - Azure (Chrome,Firefox)Autoscale Test Location (Chrome,Firefox)                            </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;location&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='location']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='analytical-review']/ul/li[2]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Location'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Traceroute'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browser'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
   </webElementXpaths>
</WebElementEntity>
